---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service-node-v4
  labels:
    pod-name: my-web-service-node-v4
spec:
  type: NodePort
  ports:
    - name: webserver-node-v4-8080
      protocol: TCP
      port: 8080
      nodePort: 30080
  selector:
    pod-name: my-web-server-node-v4

