apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
   role: webserver
  ports:
    - name: webserver-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: webserver-81
      protocol: TCP
      port: 81
      targetPort: 81

