---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service-host-node-v4
  labels:
    pod-name: my-web-service-host-node-v4
spec:
  type: NodePort
  ports:
    - name: webserver-host-node-v4-80
      protocol: TCP
      port: 80
      nodePort: 30180
  selector:
    pod-name: my-web-server-host-node-v4

