---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ft-client-pod
spec:
  selector:
    matchLabels:
      name: ft-client-pod
  template:
    metadata:
      labels:
        name: ft-client-pod
    spec:
      containers:
      - name: ft-client-pod
        image: quay.io/billy99/ft-base-image:0.6
        command:
          - /sbin/init
        imagePullPolicy: IfNotPresent
      nodeSelector:
        ft.ClientPod: client
