---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ft-http-server-pod-index-smartnic
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <title>Server - Pod Backend Reached</title>
      </head>
      <body>
        <p>This is the Server, backed by a pod</p>
      </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: ft-http-server-v4
  annotations:
    v1.multus-cni.io/default-network: default/ftnetattach
  labels:
    pod-name: ft-http-server-v4
spec:
  containers:
  - name: ft-http-server-v4
    image: registry.access.redhat.com/ubi8/python-38
    volumeMounts:
    - name: ft-http-server-index
      mountPath: /etc/httpserver/index.html
      subPath: index.html
      readOnly: true
    command:
      - "python"
    args: ["-m", "http.server", "8080", "--directory", "/etc/httpserver/"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        openshift.io/mlnx_bf: '1'
      limits:
        openshift.io/mlnx_bf: '1'
  nodeSelector:
    ft.ServerPod: server
  volumes:
  - name: ft-http-server-index
    configMap:
      defaultMode: 0644
      name: ft-http-server-pod-index-smartnic
