---
apiVersion: v1
kind: Service
metadata:
  name: web-service-clusterip-v4
  labels:
    pod-name: my-web-service-clusterip-v4
spec:
  type: ClusterIP
  ports:
    - name: web-server-clusterip-v4-8080
      protocol: TCP
      port: 8080
  selector:
    pod-name: my-web-server-v4